# Generated by Django 5.1.7 on 2025-04-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='default@example.com', error_messages={'blank': 'Email cannot be empty.', 'unique': 'Email already exists.'}, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username cannot be empty.', 'unique': 'Username already exists.'}, max_length=30, unique=True),
        ),
    ]
