# Generated by Django 5.1.7 on 2025-04-21 14:38

import article.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('picture', models.ImageField(blank=True, upload_to='author_image_upload_to')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=43)),
                ('description', models.TextField(max_length=95)),
                ('introduction', models.TextField(max_length=330)),
                ('first_paragraph', models.TextField()),
                ('first_image', models.ImageField(blank=True, upload_to='article_file_upload_to')),
                ('second_paragraph', models.TextField()),
                ('second_image', models.ImageField(blank=True, upload_to='article_file_upload_to')),
                ('third_paragraph', models.TextField()),
                ('third_image', models.ImageField(blank=True, upload_to='article_file_upload_to')),
                ('slug', models.SlugField(blank=True)),
                ('is_bestSeller', models.BooleanField(default=False)),
                ('num_of_reviews', models.PositiveBigIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('card', models.CharField(default='regular', max_length=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.author')),
                ('subject', models.ManyToManyField(to='article.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('username', models.CharField(max_length=40)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='subject',
            field=models.ManyToManyField(to='article.subject'),
        ),
    ]
