# Generated by Django 5.1.7 on 2025-04-21 19:48

import article.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, upload_to=article.models.Author.author_image_upload_to),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='article.article'),
        ),
    ]
