# Generated by Django 5.1.7 on 2025-04-22 19:57

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_author_picture_alter_feedback_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='first_image',
            field=models.FileField(blank=True, upload_to='article_file_upload_to'),
        ),
        migrations.AlterField(
            model_name='article',
            name='second_image',
            field=models.FileField(blank=True, upload_to='article_file_upload_to'),
        ),
        migrations.AlterField(
            model_name='article',
            name='third_image',
            field=models.FileField(blank=True, upload_to='article_file_upload_to'),
        ),
    ]
