# Generated by Django 5.1.7 on 2025-04-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_first_image_alter_article_second_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='first_image',
            new_name='first_media',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='second_image',
            new_name='second_media',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='third_image',
            new_name='third_media',
        ),
    ]
