# Generated by Django 5.1.7 on 2025-05-02 15:44

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='first_media',
            field=models.FileField(blank=True, null=True, upload_to=article.models.article_file_upload_to),
        ),
        migrations.AlterField(
            model_name='article',
            name='second_media',
            field=models.FileField(blank=True, null=True, upload_to=article.models.article_file_upload_to),
        ),
        migrations.AlterField(
            model_name='article',
            name='third_media',
            field=models.FileField(blank=True, null=True, upload_to=article.models.article_file_upload_to),
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=article.models.author_image_upload_to),
        ),
    ]
