# Generated by Django 5.1.7 on 2025-05-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_diseaseimage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaseimage',
            name='category',
        ),
        migrations.AddField(
            model_name='disease',
            name='category',
            field=models.CharField(default='leaf', max_length=20),
        ),
    ]
