name: Run Tests

on:
  push:
    branches:
      - main            # Add the main branch here
  pull_request:
    branches:
      - main            # Add the main branch here

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      AWS_STORAGE_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Set environment variables
      - name: Set environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "DJANGO_SETTINGS_MODULE=backend_main.settings" >> $GITHUB_ENV

      # Install Python dependencies (Backend)
      - name: Install dependencies (Backend)
        run: |
          cd backend-drf
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django

      # Run backend tests
      - name: Run backend tests
        run: |
          cd backend-drf
          pytest --maxfail=5 --disable-warnings --verbose
        env:
          DB_NAME: test_db
          DB_USER: test_user
          DB_PASSWORD: test_pass
          DB_HOST: localhost

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  

      # Install Node.js dependencies (Frontend)
      - name: Install dependencies (Frontend)
        run: |
          cd frontend-react
          npm install

      # Run frontend tests
      - name: Run frontend tests
        run: |
          cd frontend-react
          npm test -- --maxWorkers=2 --ci --reporters=default


